### ISSUE TITLE
Fibers error while installing

### ISSUE THREAD

**Issue by snowy1000** [nuxt-community/vuetify-module#345]
I'm trying to install latest version. But getting the error belove, about fibers.

```
se )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
Bu çözümde projeler tek tek derlenir. Paralel bir derlemeyi etkinleştirmek için lütfen "/m" anahtarını ekleyin.
  fibers.cc
  coroutine.cc
  win_delay_load_hook.cc
d:\love\djs-web-nuxt\node_modules\fibers\src\coroutine.cc(153): warning C4552: '!': ifade sonucu kullanılmıyor [D:\love\djs-web-nuxt\node_modules\fibers\build\fibers.vcxproj]
  coro.c
C:\\Users\\ultro\\AppData\\Local\\node-gyp\\Cache\\13.13.0\\x64\\node.lib : fatal error LNK1127: Kitapl²k bozuk [D:\love\djs-web-nuxt\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\love\djs-web-nuxt\node_modules\fibers
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN ts-jest@25.5.1 requires a peer of jest@>=25 <26 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@25.5.1 requires a peer of typescript@>=3.4 <4.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-jest@4.0.0-beta.3 requires a peer of jest@^25.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by wemod123** [comment]
same issue, specificlly on windows system

**Comment by snowy1000** [comment]
> same issue, specificlly on windows system

For you and anyone that will come here later, downgrading your Node to LTS (currently 12.18.1 => Click [here](https://nodejs.org/dist/v12.18.1/node-v12.18.1-x64.msi) for an instant download link) and your problem will be solved.

**Comment by samaaHelmi** [comment]
[all/latest node version download links](https://nodejs.org/en/download/releases/)

**Comment by EthanHaid** [comment]
Is this fibers dependency going to be removed / fixed? 
Downgrading to node 12.18.1 worked for me, but it's a temporary workaround
