### ISSUE TITLE
Error when treeShaking is enabled on Docker environment

### ISSUE THREAD

**Issue by igolka97** [nuxt-community/vuetify-module#399]
**Module version**
1.11.2

**Describe the bug**
I using docker-compose for dev. While launching `yarn dev` on docker environment with `node:alpine` or `node:lts-alpine` image  getting too much errors like:
```
ERROR  Error: Cannot find module '/app/node_modules/fibers/bin/linux-x64-79-musl/fibers'
Require stack:
- /app/node_modules/fibers/fibers.js
- /app/node_modules/sass-loader/dist/getSassOptions.js
- /app/node_modules/sass-loader/dist/index.js
- /app/node_modules/sass-loader/dist/cjs.js
- /app/node_modules/loader-runner/lib/loadLoader.js
- /app/node_modules/loader-runner/lib/LoaderRunner.js
- /app/node_modules/webpack/lib/NormalModule.js
- /app/node_modules/webpack/lib/NormalModuleFactory.js
- /app/node_modules/webpack/lib/Compiler.js
- /app/node_modules/webpack/lib/webpack.js
- /app/node_modules/@nuxt/webpack/dist/webpack.js
- /app/node_modules/@nuxt/cli/dist/cli-index.js
- /app/node_modules/@nuxt/cli/dist/cli.js
- /app/node_modules/nuxt/bin/nuxt.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getSassOptions (/app/node_modules/sass-loader/dist/getSassOptions.js:49:25)
    at Object.loader (/app/node_modules/sass-loader/dist/index.js:48:51)
    at LOADER_EXECUTION (/app/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
```

**To Reproduce**
https://github.com/igolka97/vuetify-docker-bug

1. Install Docker and Git (if you didnt do it before)
2. `git clone https://github.com/igolka97/vuetify-docker-bug.git`
3. `cd vuetify-docker-bug`
4. `yarn`
5. `docker-compose up`

**Expected behavior**
No errors

**Additional context**
Operating system: Mac

**Comment by igolka97** [comment]
Founded solution: downgrade node version from 15 to 12-alpine.

Seems that problem was caused by fsevents:
`fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`

But fsevents package for OS X, and I dont now how it related.
