### ISSUE TITLE
Move fibers to dev dependency. Building docker images requires python and gcc+

### ISSUE THREAD

**Issue by Akkarine** [nuxt-community/vuetify-module#402]
I have an error in my CI/CD pipeline when I use docker image `node:lts-alpine3.12`, because it does not have `python` and `gcc+` libs. Theese libs are dependencies for fibers and will not used after build, so It's useless space consumer in my final image. I count this as bug, because, for my surprise, previous builds were fine.

<details>
<summary>docker build log</summary>

```shell
#9 71.94 > fibers@4.0.3 install /app/node_modules/fibers
#9 71.94 > node build.js || nodejs build.js
#9 71.94
#9 72.10 gyp ERR! find Python 
#9 72.11 gyp ERR! find Python Python is not set from command line or npm configuration
#9 72.11 gyp ERR! find Python Python is not set from environment variable PYTHON
#9 72.11 gyp ERR! find Python checking if "python" can be used
#9 72.11 gyp ERR! find Python - "python" is not in PATH or produced an error
#9 72.11 gyp ERR! find Python checking if "python2" can be used
#9 72.11 gyp ERR! find Python - "python2" is not in PATH or produced an error
#9 72.11 gyp ERR! find Python checking if "python3" can be used
#9 72.11 gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 72.11 gyp ERR! find Python 
#9 72.11 gyp ERR! find Python **********************************************************
#9 72.11 gyp ERR! find Python You need to install the latest version of Python.
#9 72.11 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 72.11 gyp ERR! find Python you can try one of the following options:
#9 72.11 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 72.11 gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 72.11 gyp ERR! find Python - Set the environment variable PYTHON
#9 72.11 gyp ERR! find Python - Set the npm configuration variable python:
#9 72.11 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 72.11 gyp ERR! find Python For more information consult the documentation at:
#9 72.11 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 72.11 gyp ERR! find Python **********************************************************
#9 72.11 gyp ERR! find Python 
#9 72.11 gyp ERR! configure error 
#9 72.11 gyp ERR! stack Error: Could not find any Python installation to use
#9 72.11 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#9 72.11 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#9 72.11 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#9 72.11 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#9 72.11 gyp ERR! stack     at exithandler (child_process.js:315:5)
#9 72.11 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
#9 72.11 gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
#9 72.11 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
#9 72.11 gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
#9 72.11 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
#9 72.11 gyp ERR! System Linux 4.15.0-122-generic
#9 72.11 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
#9 72.11 gyp ERR! cwd /app/node_modules/fibers
#9 72.11 gyp ERR! node -v v14.15.1
#9 72.11 gyp ERR! node-gyp -v v5.1.0
#9 72.11 gyp ERR! not ok 
#9 72.11 node-gyp exited with code: 1
#9 72.11 Please make sure you are using a supported platform and node version. If you
#9 72.11 would like to compile fibers on this machine please make sure you have setup your
#9 72.11 build environment--
#9 72.11 Windows + OS X instructions here: https://github.com/nodejs/node-gyp
#9 72.11 Ubuntu users please run: `sudo apt-get install g++ build-essential`
#9 72.11 RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
#9 72.11 Alpine users please run: `sudo apk add python make g++`
#9 72.26 gyp ERR! find Python 
#9 72.26 gyp ERR! find Python Python is not set from command line or npm configuration
#9 72.26 gyp ERR! find Python Python is not set from environment variable PYTHON
#9 72.26 gyp ERR! find Python checking if "python" can be used
#9 72.26 gyp ERR! find Python - "python" is not in PATH or produced an error
#9 72.26 gyp ERR! find Python checking if "python2" can be used
#9 72.26 gyp ERR! find Python - "python2" is not in PATH or produced an error
#9 72.26 gyp ERR! find Python checking if "python3" can be used
#9 72.26 gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 72.26 gyp ERR! find Python 
#9 72.26 gyp ERR! find Python **********************************************************
#9 72.26 gyp ERR! find Python You need to install the latest version of Python.
#9 72.26 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 72.26 gyp ERR! find Python you can try one of the following options:
#9 72.26 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 72.26 gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 72.26 gyp ERR! find Python - Set the environment variable PYTHON
#9 72.26 gyp ERR! find Python - Set the npm configuration variable python:
#9 72.26 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 72.26 gyp ERR! find Python For more information consult the documentation at:
#9 72.26 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 72.26 gyp ERR! find Python **********************************************************
#9 72.26 gyp ERR! find Python 
#9 72.26 gyp ERR! configure error 
#9 72.26 gyp ERR! stack Error: Could not find any Python installation to use
#9 72.26 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#9 72.26 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#9 72.26 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#9 72.26 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#9 72.26 gyp ERR! stack     at exithandler (child_process.js:315:5)
#9 72.26 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
#9 72.26 gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
#9 72.26 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
#9 72.26 gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
#9 72.26 gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
#9 72.26 gyp ERR! System Linux 4.15.0-122-generic
#9 72.26 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
#9 72.26 gyp ERR! cwd /app/node_modules/fibers
#9 72.26 gyp ERR! node -v v14.15.1
#9 72.26 gyp ERR! node-gyp -v v5.1.0
#9 72.26 gyp ERR! not ok 
#9 72.26 node-gyp exited with code: 1
#9 72.26 Please make sure you are using a supported platform and node version. If you
#9 72.26 would like to compile fibers on this machine please make sure you have setup your
#9 72.26 build environment--
#9 72.26 Windows + OS X instructions here: https://github.com/nodejs/node-gyp
#9 72.26 Ubuntu users please run: `sudo apt-get install g++ build-essential`
#9 72.26 RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
#9 72.26 Alpine users please run: `sudo apk add python make g++`
#9 73.38 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
#9 73.38 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 73.38 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
#9 73.38 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 73.39 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
#9 73.39 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 73.40 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@vuepress/core/node_modules/chokidar/node_modules/fsevents):
#9 73.40 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 73.41 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
#9 73.41 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
#9 73.42 npm WARN vue-cli-plugin-apollo@0.22.2 requires a peer of @vue/cli-shared-utils@^3.0.0 || ^4.0.0-0 but none is installed. You must install peer dependencies yourself.
#9 73.42 npm WARN apollo-link-persisted-queries@0.2.2 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.43 npm WARN graphql-subscriptions@1.1.0 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.44 npm WARN ts-node@8.10.2 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself.
#9 73.45 npm WARN @apollographql/graphql-language-service-interface@2.0.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.46 npm WARN @apollographql/graphql-language-service-parser@2.0.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.47 npm WARN @apollographql/graphql-language-service-types@2.0.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.47 npm WARN @apollographql/graphql-language-service-utils@2.0.2 requires a peer of graphql@^0.12.0 || ^0.13.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.48 npm WARN graphql-upload@8.1.0 requires a peer of graphql@0.13.1 - 14 but none is installed. You must install peer dependencies yourself.
#9 73.49 npm WARN eslint-config-standard@16.0.2 requires a peer of eslint@^7.12.1 but none is installed. You must install peer dependencies yourself.
#9 73.50 npm WARN eslint-plugin-vue@7.1.0 requires a peer of eslint@^6.2.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
#9 73.50 
#9 73.51 npm ERR! code ELIFECYCLE
#9 73.51 npm ERR! errno 1
#9 73.52 npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
#9 73.52 npm ERR! Exit status 1
#9 73.52 npm ERR! 
#9 73.52 npm ERR! Failed at the fibers@4.0.3 install script.
#9 73.52 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#9 73.55 
#9 73.55 npm ERR! A complete log of this run can be found in:
#9 73.55 npm ERR!     /root/.npm/_logs/2020-11-25T07_44_31_834Z-debug.log
#9 ERROR: executor failed running [/bin/sh -c npm install --no-audit && npm audit fix]: runc did not terminate sucessfully
------
 > [base 5/5] RUN npm install --no-audit && npm audit fix:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c npm install --no-audit && npm audit fix]: runc did not terminate sucessfully
Cleaning up file based variables
00:02
ERROR: Job failed: exit code 1
```
</details>

You have an open PR that solves this problem: #367
And in past you had fibers as optional: #179

Also consider other issues you solving with this PR: #179, #390

Vuetify itself got rid of it: https://github.com/vuetifyjs/vuetify/pull/12252

Not to mention that creator of fibers marked this library as obsolete at the very beginning of [readme](https://github.com/laverdet/node-fibers)!

**Comment by EthanHaid** [comment]
+1

**Comment by Akkarine** [comment]
Looks like not actual due https://github.com/nuxt-community/vuetify-module/pull/390
