### ISSUE TITLE
Generate fails on VCarousel component

### ISSUE THREAD

**Issue by saike** [nuxt-community/vuetify-module#438]
**Module version**
^1.11.3
**Describe the bug**

`npm run generate` command fails with sass error

**To Reproduce**

1. add VCarousel to app
2. run in shell `npm run generate'

**Expected behavior**
App built success

**Screenshots**
![image](https://user-images.githubusercontent.com/1619473/115109260-59b9a880-9f7d-11eb-8f26-c406ebc86f41.png)

**Additional context**
I tried to change vue.config.js, and installed sass

**Comment by saike** [comment]
i manually setted `treeShake: false` and error dessapeared. I don't know can this classified as bug. If you think not, close this issue.

**Comment by larzon83** [comment]
Can you show your package.json?

**Comment by saike** [comment]
`
{
  "name": "takeswap-frontend",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/vuetify": "^1.11.3",
    "core-js": "^3.9.1",
    "nuxt": "^2.15.3",
    "vuetify": "^2.4.9"
  }
}

`

**Comment by larzon83** [comment]
devDeps too please.
BTW: @nuxtjs/vuetify and vuetify should be in devDeps, not deps.

**Comment by DevSchmidtchen** [comment]
I am getting a similar error since today (it worked perfectly before), but with other components (VSelect and VWindow) and by using `nuxt build`. Treeshaking doesn't change anything in my case. What's interesting there, is that this error doesn't occur locally, but only by running with a Dockerfile (same commands) on Google Cloud Run.

```
ERROR in ./node_modules/vuetify/src/components/VSelect/VSelect.sass
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
   ╷
70 │       position: relative
   │                         ^
   ╵
  node_modules/vuetify/src/components/VSelect/VSelect.sass 70:25  root stylesheet
    at /usr/src/app/node_modules/webpack/lib/NormalModule.js:316:20
    at /usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /usr/src/app/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/usr/src/app/node_modules/sass/sass.dart.js:92439:16)
    at _render_closure1.call$2 (/usr/src/app/node_modules/sass/sass.dart.js:80990:12)
    at _RootZone.runBinary$3$3 (/usr/src/app/node_modules/sass/sass.dart.js:27220:18)
    at _FutureListener.handleError$1 (/usr/src/app/node_modules/sass/sass.dart.js:25776:19)
    at _Future__propagateToListeners_handleError.call$0 (/usr/src/app/node_modules/sass/sass.dart.js:26074:49)
    at Object._Future__propagateToListeners (/usr/src/app/node_modules/sass/sass.dart.js:4536:77)
    at _Future._completeError$2 (/usr/src/app/node_modules/sass/sass.dart.js:25906:9)
    at _AsyncAwaitCompleter.completeError$2 (/usr/src/app/node_modules/sass/sass.dart.js:25560:12)
    at Object._asyncRethrow (/usr/src/app/node_modules/sass/sass.dart.js:4335:17)
    at /usr/src/app/node_modules/sass/sass.dart.js:12852:20
    at _wrapJsFunctionForAsync_closure.$protected (/usr/src/app/node_modules/sass/sass.dart.js:4360:15)
 @ ./node_modules/vuetify/lib/components/VSelect/VSelect.js 56:0-54
 @ ./node_modules/vuetify/lib/components/VSelect/index.js
 @ ./src/components/atoms/StyleFilter.vue
 @ ./.nuxt/components/plugin.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

ERROR in ./node_modules/vuetify/src/components/VWindow/VWindow.sass
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected identifier.
  ╷
6 │   overflow: hidden
  │                   ^
  ╵
  node_modules/vuetify/src/components/VWindow/VWindow.sass 6:19  root stylesheet
    at /usr/src/app/node_modules/webpack/lib/NormalModule.js:316:20
    at /usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/usr/src/app/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /usr/src/app/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/usr/src/app/node_modules/sass/sass.dart.js:92439:16)
    at _render_closure1.call$2 (/usr/src/app/node_modules/sass/sass.dart.js:80990:12)
    at _RootZone.runBinary$3$3 (/usr/src/app/node_modules/sass/sass.dart.js:27220:18)
    at _FutureListener.handleError$1 (/usr/src/app/node_modules/sass/sass.dart.js:25776:19)
    at _Future__propagateToListeners_handleError.call$0 (/usr/src/app/node_modules/sass/sass.dart.js:26074:49)
    at Object._Future__propagateToListeners (/usr/src/app/node_modules/sass/sass.dart.js:4536:77)
    at _Future._completeError$2 (/usr/src/app/node_modules/sass/sass.dart.js:25906:9)
    at _AsyncAwaitCompleter.completeError$2 (/usr/src/app/node_modules/sass/sass.dart.js:25560:12)
    at Object._asyncRethrow (/usr/src/app/node_modules/sass/sass.dart.js:4335:17)
    at /usr/src/app/node_modules/sass/sass.dart.js:12852:20
    at _wrapJsFunctionForAsync_closure.$protected (/usr/src/app/node_modules/sass/sass.dart.js:4360:15)
 @ ./node_modules/vuetify/lib/components/VWindow/VWindow.js 17:0-54
 @ ./node_modules/vuetify/lib/components/VTabs/VTabsItems.js
 @ ./node_modules/vuetify/lib/components/VTabs/VTabs.js
 @ ./node_modules/vuetify/lib/components/VTabs/index.js
 @ ./src/pages/_username/beats/_id.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js
```

**Comment by Semkoo** [comment]
> i manually setted `treeShake: false` and error disappeared. I don't know can this classified as bug. If you think not, close this issue.

This worked on my end, but what if you are declaring a custom SASS variable how its doc [here](https://vuetifyjs.com/en/features/sass-variables/#nuxt-install)

**Comment by DevSchmidtchen** [comment]
`treeShake: false` did the trick for me as well (I just didn't realise). But this shouldn't be the final solution, treeshaking should be enabled at the end...
