### ISSUE TITLE
"SassError: @use rules must be written before any other rules" when generating static website

### ISSUE THREAD

**Issue by andresilva-cc** [nuxt-community/vuetify-module#450]
**Module version**
1.11.3

**Describe the bug**
When generating a static version of the project with `npm run generate`, the following error is generated:

```
ERROR in ./node_modules/vuetify/src/components/VGrid/VGrid.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VGrid/VGrid.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
3 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VGrid/VGrid.sass 3:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VGrid/VGrid.sass 4:14-204
 @ ./node_modules/vuetify/lib/components/VGrid/VContainer.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./layouts/default.vue
 @ ./node_modules/.cache/nuxt/App.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

ERROR in ./node_modules/vuetify/src/components/VGrid/_grid.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VGrid/_grid.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
3 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VGrid/_grid.sass 3:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VGrid/_grid.sass 4:14-204
 @ ./node_modules/vuetify/lib/components/VGrid/VSpacer.js
 @ ./node_modules/vuetify/lib/components/VGrid/index.js
 @ ./layouts/default.vue
 @ ./node_modules/.cache/nuxt/App.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

ERROR in ./node_modules/vuetify/src/components/VToolbar/VToolbar.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VToolbar/VToolbar.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
3 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VToolbar/VToolbar.sass 3:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VToolbar/VToolbar.sass 4:14-207
 @ ./node_modules/vuetify/lib/components/VToolbar/VToolbar.js
 @ ./node_modules/vuetify/lib/components/VToolbar/index.js
 @ ./layouts/default.vue
 @ ./node_modules/.cache/nuxt/App.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

ERROR in ./node_modules/vuetify/src/components/VBtn/VBtn.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./node_modules/vuetify/src/components/VBtn/VBtn.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: @use rules must be written before any other rules.
  ╷
4 │ @use 'sass:math'
  │ ^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/src/components/VBtn/VBtn.sass 4:1  root stylesheet
 @ ./node_modules/vuetify/src/components/VBtn/VBtn.sass 4:14-203
 @ ./node_modules/vuetify/lib/components/VBtn/VBtn.js
 @ ./node_modules/vuetify/lib/components/VBtn/index.js
 @ ./layouts/default.vue
 @ ./node_modules/.cache/nuxt/App.js
 @ ./node_modules/.cache/nuxt/index.js
 @ ./node_modules/.cache/nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./node_modules/.cache/nuxt/client.js

 FATAL  Nuxt build error                                                                                                   14:26:15

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async ensureBuild (node_modules/@nuxt/cli/dist/cli-generate.js:145:3)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:283:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯
```
**To Reproduce**
1. Create a new Nuxt.js project with `npx create-nuxt-app project-name`
2. In the setup, choose Vuetify as the **UI framework** and Static as **Deployment target**
3. Inside the project directory, run `npm run generate` 

**Expected behavior**
It is expected that the build completes without any error, mainly that this is a blank project.

**Comment by RyanCasas** [comment]
I can confirm this is an issue.

My current workaround is to force both `sass` and `vuetify` to be downgraded, which is far from ideal, by writing this into the `package.json`:

```json
"resolutions": {
    "@nuxtjs/vuetify/**/sass": "~1.32.0",
    "vuetify": "2.5.1"
}
```

**Comment by andresilva-cc** [comment]
> I can confirm this is an issue.
> 
> My current workaround is to force both `sass` and `vuetify` to be downgraded, which is far from ideal, by writing this into the `package.json`:
> 
> ```json
> "resolutions": {
>     "@nuxtjs/vuetify/**/sass": "~1.32.0",
>     "vuetify": "2.5.1"
> }
> ```

Unfortunately, that does not work for me, it generates the same error.

**Comment by RyanCasas** [comment]
> > I can confirm this is an issue.
> > My current workaround is to force both `sass` and `vuetify` to be downgraded, which is far from ideal, by writing this into the `package.json`:
> > ```json
> > "resolutions": {
> >     "@nuxtjs/vuetify/**/sass": "~1.32.0",
> >     "vuetify": "2.5.1"
> > }
> > ```
> 
> Unfortunately, that does not work for me, it generates the same error.

You'd need to run either `yarn` or `npm i` after that.

**Comment by andresilva-cc** [comment]
> > > I can confirm this is an issue.
> > > My current workaround is to force both `sass` and `vuetify` to be downgraded, which is far from ideal, by writing this into the `package.json`:
> > > ```json
> > > "resolutions": {
> > >     "@nuxtjs/vuetify/**/sass": "~1.32.0",
> > >     "vuetify": "2.5.1"
> > > }
> > > ```
> > 
> > 
> > Unfortunately, that does not work for me, it generates the same error.
> 
> Try to run either `yarn` or `npm i` after editing the `package.json`, and let me know if that works for you.

Yes, I tried erasing both `package-lock.json` and `node_modules` and running `npm i` again but it doesn't work

**Comment by RyanCasas** [comment]
It sure works for me with the workaround: https://github.com/RyanCasas/nuxt-vuetify-sass-error-test
What settings did you put in? These are mine:
![image](https://user-images.githubusercontent.com/11211891/120370046-68cd9d80-c314-11eb-9ca7-df17478a9a82.png)

Did you use Universal or SPA?

**Comment by andresilva-cc** [comment]
![Captura de Tela 2021-06-01 às 15 27 59](https://user-images.githubusercontent.com/15927886/120372794-03ff4c80-c2ee-11eb-816a-bd2916983ade.png)

Universal.

**Comment by andrelandgraf** [comment]
I have the same issue with @nuxtjs/vuetify: ^1.11.3.

```ssh
SassError: @use rules must be written before any other rules.
4 │ @use 'sass:math'
```

I am using npm not yarn, so resolution is not an option for me but manually installing them did the job:

```
npm i -D sass@~1.32.0 vuetify@2.5.1                                           
```

**Comment by polymer-coder** [comment]
> npm i -D sass@~1.32.0 vuetify@2.5.1

Vuetify is a devDependancy?

**Comment by larzon83** [comment]
>  Vuetify is a devDependancy? 

Yes

**Comment by andrelandgraf** [comment]
I was able to create a temporary workaround to fix this issue in my pipelines.

I don't know if all of those changes are necessary but the following changes fixed it for me: 

```
@nuxt/content: ^1.5.3  -> ^1.14.0
nuxt: ^2.2.0 -> ^2.15.3
@nuxt/types: ^2.15.6" -> ^2.15.3
```

Also, I still have sass@~1.32.0 and vuetify@2.5.1  in my devDependencies for now.

I hope that helps others facing this issue!
